[package]
name = "rapier-example"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/rapier-example"
# macroquad 0.3.26 requires MSRV 1.73
rust-version = "1.73"
description = "Rapier Physics with Macroquad ğŸ—¡ï¸ building a basic game physics simulation in Rust using rapier physics and Macroquad for rendering ğŸ–¥ï¸"

[dependencies]
crossbeam = "0.8.4"
egui = "0.22.0"
egui-macroquad = "0.15"
macroquad = { version = "0.3.26", default-features = false }
rand = "0.8.5"
rand_distr = "0.4.3"
rapier2d = { version = "0.21.0", features = ["simd-stable"] }
